steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'start']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'helloWorld'
      - '--entry-point'
      - 'app'
      - '--runtime'
      - 'nodejs20'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--region'
      - 'us-central1'
timeout: '400s'
options:
  logging: CLOUD_LOGGING_ONLY
